In [3]:
import pandas as pd
import numpy as np

In [4]:
fon1 = pd.read_csv('C:/Users/nout/Desktop/попытка номер 5/Уроки/GitHub/Python-Maksim/Dust/Data/TEST_5_001 (1).csv', skiprows=36, index_col='Elapsed Time [s]')
izm1 = pd.read_csv('C:/Users/nout/Desktop/попытка номер 5/Уроки/GitHub/Python-Maksim/Dust/Data/TEST_5_002.csv', skiprows=36, index_col='Elapsed Time [s]')
fon1.head()

,PM1 [mg/m3],PM2.5 [mg/m3],PM4 [mg/m3],PM10 [mg/m3],TOTAL [mg/m3],Alarms,Errors
Elapsed Time [s],,,,,,,
1,0.027,0.029,0.035,0.083,0.185,NaN,NaN
2,0.026,0.028,0.031,0.057,0.092,NaN,NaN
3,0.023,0.024,0.027,0.037,0.037,NaN,NaN
4,0.041,0.046,0.060,0.124,0.131,NaN,NaN
5,1.390,1.450,1.680,2.730,2.880,PM1,NaN

In [5]:
izm1.head()

,PM1 [mg/m3],PM2.5 [mg/m3],PM4 [mg/m3],PM10 [mg/m3],TOTAL [mg/m3],Alarms,Errors
Elapsed Time [s],,,,,,,
1,0.075,0.085,0.115,0.245,0.265,NaN,NaN
2,0.084,0.093,0.119,0.257,0.281,NaN,NaN
3,0.080,0.091,0.122,0.252,0.347,NaN,NaN
4,0.072,0.082,0.117,0.243,0.287,NaN,NaN
5,0.070,0.080,0.111,0.237,0.275,NaN,NaN

In [6]:
fon1 = fon1.drop(['Alarms','Errors'], axis=1)
izm1 = izm1.drop(['Alarms','Errors'], axis=1)

In [7]:
desp = - izm1 + fon1
desp

,PM1 [mg/m3],PM2.5 [mg/m3],PM4 [mg/m3],PM10 [mg/m3],TOTAL [mg/m3]
Elapsed Time [s],,,,,
1,-0.048,-0.056,-0.080,-0.162,-0.080
2,-0.058,-0.065,-0.088,-0.200,-0.189
3,-0.057,-0.067,-0.095,-0.215,-0.310
4,-0.031,-0.036,-0.057,-0.119,-0.156
5,1.320,1.370,1.569,2.493,2.605
...,...,...,...,...,...
296,0.743,0.894,1.367,3.313,3.553
297,0.731,0.884,1.347,3.366,3.606
298,0.741,0.894,1.376,3.175,3.375
299,0.751,0.899,1.377,3.096,3.375
300,0.791,0.942,1.429,3.219,3.453

In [8]:
#desp.sample(20)

In [20]:
desp.apply(lambda x: x + 10 if x > 0 else x, axis=1)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().